bank_reviews:  # This matches the profile name in dbt_project.yml
  target: dev
  outputs:
    dev:
      type: postgres  # Change this to your database type if different
      host: rvhyajijhxfxhauvrydy.supabase.co
      port: 5432
      user: postgres  # Matches your user from staging.yml
      password: highlevel@2025
      dbname: bank_reviews_dw  # Matches your database name from staging.yml
      schema: public    # Matches your schema name from staging.yml
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10 