etl_dw:
  target: dev
  outputs:
    dev:
      type: postgres
      host: rvhyajijhxfxhauvrydy.supabase.co
      user: postgres         # <-- CHANGE THIS
      password: highlevel@2025     # <-- CHANGE THIS
      port: 5432
      dbname: bank_reviews_dw                    # <-- CHANGE IF NEEDED
      schema: public                      # or your schema name
      sslmode: require