version: 2

sources:
  - name: raw
    database: bank_reviews_dw
    schema: public
    tables:
      - name: bank_reviews
        columns:
          - name: bank_name
            description: Name of the bank
          - name: branch_name
            description: Name of the branch
          - name: location
            description: Location of the branch
          - name: review_text
            description: Text content of the review
          - name: rating
            description: Rating given by the customer (1-5)
          - name: review_date
            description: Date when the review was posted

models:
  - name: stg_bank_reviews
    description: "Staging model for bank reviews data"
    columns:
      - name: bank_name
        description: "Name of the bank"
        tests:
          - not_null
      - name: branch_name
        description: "Name of the branch"
        tests:
          - not_null
      - name: location
        description: "Location of the branch"
        tests:
          - not_null
      - name: review_text
        description: "Text content of the review"
      - name: rating
        description: "Rating given by the customer (1-5)"
        tests:
          - not_null
      - name: review_date
        description: "Date when the review was posted"
        tests:
          - not_null