etl_dw:
  target: postgres
  outputs:
    dev:
      type: postgres
      host: localhost
      user: zakaria
      password: highlevel
      port: 5432
      dbname: bank_reviews_dw
      schema: public